# Generated by Django 3.1 on 2021-12-25 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название альбома')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание альбома')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фото')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, upload_to=photo.models.user_directory_path, verbose_name='Фото')),
                ('image_small', models.ImageField(blank=True, upload_to=photo.models.user_directory_path_small, verbose_name='Уменьшенное фото')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.album')),
                ('tags', models.ManyToManyField(blank=True, to='photo.Tags', verbose_name='Тэги для альбома')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photo.Tags', verbose_name='Тэги для альбома'),
        ),
    ]
