# Generated by Django 3.1 on 2021-12-19 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-created_at',), 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='albumtags',
            options={'verbose_name': 'Тэг альбомов', 'verbose_name_plural': 'Тэги для альбомов'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-created_at',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='phototags',
            options={'verbose_name': 'Тэг для фотографий', 'verbose_name_plural': 'Тэги для фотографий'},
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.album'),
        ),
        migrations.AddField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to=photo.models.user_directory_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_small',
            field=models.ImageField(blank=True, upload_to=photo.models.user_directory_path_small, verbose_name='Уменьшенное фото'),
        ),
    ]
