# Generated by Django 3.1 on 2021-12-27 02:45

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to=photo.models.user_directory_path, validators=[photo.models.validate_image], verbose_name='Фото'),
        ),
    ]
