# Generated by Django 3.1 on 2021-12-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='albumtags',
            options={'verbose_name': 'Тэг альбомов', 'verbose_name_plural': 'Тэги для альбомов'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='phototags',
            options={'verbose_name': 'Тэг для фотографий', 'verbose_name_plural': 'Тэги для фотографий'},
        ),
    ]
