# Generated by Django 3.1 on 2021-12-16 15:06

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to=photo.models.user_directory_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_small',
            field=models.ImageField(blank=True, upload_to=photo.models.user_directory_path, verbose_name='Фото'),
        ),
    ]
